apiVersion: 0.1.0
environments:
  dev:
    destination:
      namespace: ks-dev
      server: https://192.168.64.93:8443
    k8sVersion: v1.8.0
    path: dev
  prod:
    destination:
      namespace: ks-prod
      server: https://192.168.64.2:8443
    k8sVersion: v1.7.0
    path: prod
kind: ksonnet.io/app
libraries:
  redis:
    gitVersion:
      commitSha: ea3408d44c2d8ea4d321364e5533d5c60e74bce0
      refSpec: master
    name: redis
    registry: incubator
name: guestbook
registries:
  incubator:
    gitVersion:
      commitSha: ea3408d44c2d8ea4d321364e5533d5c60e74bce0
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
